### ISSUE TITLE
Error while calling cublasSgemm

### ISSUE THREAD

**Issue by zhang-yun-peng** [coneypo/Dlib_face_recognition_from_camera#12]
当我用ubuntu18.04+cuda10.1+dlib19.17+rtx2080运行程序是总是报错：Error while calling cublasSgemm（）in file xx/cuda/cublas_dlibapi.cpp. code:13,reason:a call to cublas failed.请问这种情况如何解决？

**Comment by coneypo** [comment]
这是你环境的问题，我没配CUDA

**Comment by zhang-yun-peng** [comment]
谢谢回复，我已经跑起来了。


发自我的iPad
---Original---
