### ISSUE TITLE
有没有关于Dlib的详细算法

### ISSUE THREAD

**Issue by hongjiawang** [coneypo/Dlib_face_recognition_from_camera#13]
首先感谢您的代码，做项目时学习了下，有几个问题请教，Dlib库里的算法去哪了解，想深入学习下。0.4那个参数是您测试得到的？’识别率是怎么测的吗？。本人在校大学生，第一次问问题，不得体请见谅

**Comment by coneypo** [comment]
**关于算法**

可以去 Dlib 的 Blog 去参考， Readme 里面也写了；

If you are interested in the algorithm of face recognition in dlib, please visit http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html for more information.

**关于阈值**

这个阈值是你自己设置的，经验参数；

Refer to http://dlib.net/face_recognition.py.html

#   When using a distance threshold of 0.6, the dlib model obtains an accuracy
#   of 99.38% on the standard LFW face recognition benchmark, which is
#   comparable to other state-of-the-art methods for face recognition as of
#   February 2017. This accuracy means that, when presented with a pair of face
#   images, the tool will correctly identify if the pair belongs to the same
#   person or is from different people 99.38% of the time.

**Comment by coneypo** [comment]
如果没有其他问题，我可以关掉这个 issue 吗

**Comment by hongjiawang** [comment]
ok thank you for your answer------------------ 原始邮件 ------------------
发件人: "Xie Zhengtian"<notifications@github.com>
发送时间: 2019年7月10日(星期三) 上午9:46
收件人: "coneypo/Dlib_face_recognition_from_camera"<Dlib_face_recognition_from_camera@noreply.github.com>;
抄送: "hongjiawang"<577676030@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [coneypo/Dlib_face_recognition_from_camera] 有没有关于Dlib的详细算法 (#13)



如果没有其他问题，我可以关掉这个 issue 吗
 
&mdash;
