### ISSUE TITLE
这个人脸识别似乎存在问题！

### ISSUE THREAD

**Issue by CH-WangMing** [coneypo/Dlib_face_recognition_from_camera#17]
该项目存在的问题：
1、在测试过程发现！当录入一张人脸！在识别过程中能精确识别到！但是，如果你把这一张人脸图片存储在手机上打开！并对准摄像头进行识别！也能识别到！那么这样就会有一个问题！不能进行动态识别！不能分辨识别的是真人的人脸、还是图片上的人脸

**Comment by coneypo** [comment]
![image](https://user-images.githubusercontent.com/7233586/76930177-e03a2b80-6920-11ea-9170-50acfaba29d8.png)
模型是2D图像特征点训练出来的，当然不能区分静态图片和动态图片，要是真正产品化肯定拿的3D的特征点，不会拿平面2D图像去train的

**Comment by CH-WangMing** [comment]
长知识！那么这样就说明这个项目的实用性不大！应该把模型改成3D的特征来做
