### ISSUE TITLE
FPS问题

### ISSUE THREAD

**Issue by aiyouwoqudi** [coneypo/Dlib_face_recognition_from_camera#19]
如何提高FPS？

**Comment by xialei2821212670** [comment]
可以使用GPU编译dlib的库开启加速，

**Comment by aiyouwoqudi** [comment]
好的，感谢

**Comment by aiyouwoqudi** [comment]
> 可以使用GPU编译dlib的库开启加速，

好的，感谢

**Comment by coneypo** [comment]
Hi,

用 OT 对后续帧做跟踪（https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/face_reco_from_camera_ot_single_person.py）
可以提高 5FPS -> 28FPS

**Comment by qdushuaicao** [comment]
感谢您的开源代码，在使用ot对后续帧做跟踪时，如果初始帧没有识别到视频中的数据库中人脸，那么将会一直显示unknown，没有了更新的过程，是否可以考虑 在跟踪多少帧后 再进行识别一次，或者您能给出个建议吗，谢谢。

**Comment by aiyouwoqudi** [comment]
收到，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xie Zhengtian"<notifications@github.com&gt;; 
发送时间: 2020年9月1日(星期二) 上午10:19
收件人: "coneypo/Dlib_face_recognition_from_camera"<Dlib_face_recognition_from_camera@noreply.github.com&gt;; 
抄送: "浮生"<192037779@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [coneypo/Dlib_face_recognition_from_camera] FPS问题 (#19)





 
Hi,
 
用 OT 对后续帧做跟踪（https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/face_reco_from_camera_ot_single_person.py）
 可以提高 5FPS -&gt; 28FPS

**Comment by coneypo** [comment]
Close this issue now;
