### ISSUE TITLE
raspbain

### ISSUE THREAD

**Issue by jwwc** [coneypo/Dlib_face_recognition_from_camera#23]
我在树莓派上运行您的程序，出现了图像化界面显示不了的问题怎么解决呢，cannot connect to X server localhost

**Comment by coneypo** [comment]
你起的是 gnome 桌面吗，你看看 “cheese” 能不能起来摄像头；

**Comment by jwwc** [comment]
没有安装桌面系统的，只有终端界面的

**Comment by coneypo** [comment]
> 没有安装桌面系统的，只有终端界面的

只有 terminal 没有桌面的话没法显示的，你先装个比如 ubuntu-desktop 桌面这种，纯 terminal 界面没法跑的，要调用摄像头起窗口

**Comment by coneypo** [comment]
如果没有其他问题我就关掉这个 issue 哦

**Comment by jwwc** [comment]
好的，谢谢，你这个有什么加速方法吗，我用树莓派玩的时候FPS只能到0.5左右



---Original---
