### ISSUE TITLE
关于识别更新问题

### ISSUE THREAD

**Issue by qdushuaicao** [coneypo/Dlib_face_recognition_from_camera#25]
感谢您的开源代码，在使用ot对后续帧做跟踪时，如果初始帧没有识别到视频中的数据库中人脸，那么将会一直显示unknown，没有了更新的过程，是否可以考虑 在跟踪多少帧后 再进行识别一次，或者您能给出个建议吗，谢谢。

**Comment by coneypo** [comment]
对的，现在对于注册和注销都是发生变化马上进行改变的；
更好的是，对于注册，如果识别出来是 Unknown，那么可以设定一个阈值 G，对于帧 N 如果后续帧 N+1 ~ N+G 都没有识别出来的话，那么就还是 unknown;
对于注销，如果目标丢失，比如人脸数减少 2->1 ，不是立马进行再次识别，而是给定一个阈值 G，如果后续帧中 N+1 ~ N+G 中仍然没有找到他，那就注销他；

我最近打一个 patch 进去；

**Comment by qdushuaicao** [comment]
非常感谢您的回答，谢谢！我再好好学习下。

**Comment by coneypo** [comment]
> 非常感谢您的回答，谢谢！我再好好学习下。

加了 re-classification 的功能： https://github.com/coneypo/Dlib_face_recognition_from_camera/commit/e9008e3ad398592d97929f0a8bc0db9866e1eed5

如果当前帧识别出来有未知人脸，那么启动   self.reclassify_interval_cnt 计数，计数到  = self.reclassify_interval = 10，那么就会重新进行识别；
