### ISSUE TITLE
打开usb摄像头过程慢

### ISSUE THREAD

**Issue by qdushuaicao** [coneypo/Dlib_face_recognition_from_camera#27]
我使用python3.8+opencv4，打开摄像头的过程大概20s左右，
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    cv2.imshow("Video", frame)
    # 读取内容
    if cv2.waitKey(10) == ord("Q"):
        break
请问下，有没有快速启动摄像头的方式

**Comment by coneypo** [comment]
需要去看 OpenCV 下面 VideoCapture 的实现，估计是硬件的问题，我这边打开摄像头都在 1s 以内；
