### ISSUE TITLE
总是提示out of range

### ISSUE THREAD

**Issue by yanggeorge** [coneypo/Dlib_face_recognition_from_camera#28]
方框一直在摄像头内，人脸拉远也不行。

**Comment by xuchaoyang123** [comment]
同问。。。  是BUG吗

**Comment by coneypo** [comment]
Hi

https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/get_faces_from_camera.py

Line 101  flag, img_rd = stream.read()        # Get camera video stream

你可以在这里打印出来拿到的摄像头窗口的尺寸，我这边是按照 640x480 做 “Out of range” 的错误检测的，或者你可以直接把这段判断给删了

**Comment by xuchaoyang123** [comment]
请问具体怎么修改啊 。代码如何修改 。

**Comment by xuchaoyang123** [comment]
我直接把这里修改了就可以了。
https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/get_faces_from_camera.py

                   # 6. 判断人脸矩形框是否超出 480x640 / If the size of ROI > 480x640
                    #if (d.right()+ww) > 640 or (d.bottom()+hh > 480) or (d.left()-ww < 0) or (d.top()-hh < 0):
                    if (d.right()+ww) < 640 or (d.bottom()+hh < 480) or (d.left()-ww < 0) or (d.top()-hh < 0):
