### ISSUE TITLE
get_faces_from_camera.py 文件有一处代码不明白

### ISSUE THREAD

**Issue by zhouweiwei-design** [coneypo/Dlib_face_recognition_from_camera#31]
def pre_work_del_old_face_folders(self):
        # 删除之前存的人脸数据文件夹, 删除 "/data_faces_from_camera/person_x/"...
        folders_rd = os.listdir(self.path_photos_from_camera)
        for i in range(len(folders_rd)):
            shutil.rmtree(self.path_photos_from_camera+folders_rd[i])
        if os.path.isfile("data/features_all.csv"):
            os.remove("data/features_all.csv")

    # 如果有之前录入的人脸, 在之前 person_x 的序号按照 person_x+1 开始录入 / Start from person_x+1
    def check_existing_faces_cnt(self):
        if os.listdir("data/data_faces_from_camera/"):
            # 获取已录入的最后一个人脸序号 / Get the order of latest person
            person_list = os.listdir("data/data_faces_from_camera/")
            person_num_list = []
            for person in person_list:
                person_num_list.append(int(person.split('_')[-1]))
            self.existing_faces_cnt = max(person_num_list)

        # 如果第一次存储或者没有之前录入的人脸, 按照 person_1 开始录入 / Start from person_1
        else:
            self.existing_faces_cnt = 0
 我不明白为什么要删除之前存的人脸数据文件夹，既然都已经删除了，为什么还会检测有没有之前录入的人脸？

**Comment by coneypo** [comment]
pre_work_del_old_face_folders() 会删除 data/data_faces_from_camera/ 下面的 person_1 ~ person_x 的文件夹，是默认打开的，你注释掉就好了；
checking_existing_faces_cnt() 检测 /data/data_faces_from_camera/ 存到 person_ 几了；

你把上面的函数注释掉就好了；

**Comment by zhouweiwei-design** [comment]
好的，那我就明白了

**Comment by coneypo** [comment]
Close this issue now;
