### ISSUE TITLE
Customize names

### ISSUE THREAD

**Issue by giangnt308** [coneypo/Dlib_face_recognition_from_camera#34]
Please help me, how to Customize names? I am beginer

**Comment by coneypo** [comment]
In https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/face_reco_from_camera.py

`#180                         # self.show_chinese_name()`

Please uncomment this function "show_chinese_name()";

And modify names in function "show_chinese_name":

`    # 修改显示人名 / Show names in chinese
    def show_chinese_name(self):
        # Default known name: person_1, person_2, person_3
        if self.current_frame_face_cnt >= 1:
            self.name_known_list[0] ='张三'.encode('utf-8').decode()
        # self.name_known_list[1] ='李四'.encode('utf-8').decode()
        # self.name_known_list[2] ='xx'.encode('utf-8').decode()
        # self.name_known_list[3] ='xx'.encode('utf-8').decode()
        # self.name_known_list[4] ='xx'.encode('utf-8').decode()`
