### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by duan348733684** [coneypo/Dlib_face_recognition_from_camera#37]
https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/master/face_reco_from_camera.py

line 108, in show_chinese_name：

self.name_known_list[1] = '张2'.encode('utf-8').decode()
IndexError: list assignment index out of range

我运行face_reco_from_camera.py 就报上面这个错误，请问这是什么问题？

**Comment by coneypo** [comment]
因为你只录入了一张人脸，所以 name_known_list 数组只有一个 [0]，你把后面的注释掉了就好，如果不需要修改已知人脸姓名，直接把 show_chinese_name 这个函数的调用那里注释掉也行；

     # 修改显示人名 / Show names in chinese
    def show_chinese_name(self):
        # Default known name: person_1, person_2, person_3
        if self.current_frame_face_cnt >= 1:
            self.name_known_list[0] ='张1'.encode('utf-8').decode()
            # self.name_known_list[1] ='张2'.encode('utf-8').decode()
            # self.name_known_list[2] ='张3'.encode('utf-8').decode()
            # self.name_known_list[3] ='张4'.encode('utf-8').decode()
            # self.name_known_list[4] ='张5'.encode('utf-8').decode()
