### ISSUE TITLE
face-reco-ot-multi-person识别多人人脸出错

### ISSUE THREAD

**Issue by hpp-xa** [coneypo/Dlib_face_recognition_from_camera#39]
当两个人同时进行识别时，一个识别显示为另一个人，一个识别显示unknown，怎么解决？

**Comment by coneypo** [comment]
我更新了代码，如果识别出来是 unknown，设置一个 reclassify-interval，如果这个阈值到了，就会重新做识别；

**Comment by coneypo** [comment]
Hi, 还有问题吗，没有的话，我关掉这个 issue 了啊 :)
