### ISSUE TITLE
更改名子

### ISSUE THREAD

**Issue by bocongju** [coneypo/Dlib_face_recognition_from_camera#45]
大佬，我想问问可以在进行人脸信息采集录入的时候就顺便设好名子吗??

**Comment by coneypo** [comment]
这是一个 UX/DX 的问题，我这里是用 opencv 的做的显示界面，然后用户输入只有按键输入比如 `if kk == ord('s'):`，没有提供输入字符，比如输入人名的接口，如果你想用丰富界面的 GUI，可以用 Qt , Tkinter 或者其他的工具去生成 GUI，输入名字之类，底层调用到这里的代码就好了；

**Comment by coneypo** [comment]
https://github.com/coneypo/Dlib_face_recognition_from_camera/commit/b519dfc0bb09c338331c70a5f803e8640ec7dc35

![image](https://user-images.githubusercontent.com/7233586/140879256-f1b9a18a-d1e6-48db-8995-e0ac76bf191d.png)

我用 tkinter 写了一个，录入的时候可以设置名字了 :)

**Comment by bocongju** [comment]
感谢大佬，不到一个礼拜就解决我的问题!!
