### ISSUE TITLE
在运行get_faces_from_camera_tkinter.py时，只出现了摄像头视频框,但Tkinter的GUI界面没有,Help

### ISSUE THREAD

**Issue by ShawnWayneDu** [coneypo/Dlib_face_recognition_from_camera#56]

**Comment by coneypo** [comment]
检查以下 Tkiner 的环境是否安装正确？是完全起不来 GUI 还是起来 GUI 上面没信息？

**Comment by ShawnWayneDu** [comment]
把process()注释掉的话 GUI能运行起来 GUI上也有信息 按键也可以用 但和摄像头合在一起就只有摄像头的视频以及矩形框的人脸检测

**Comment by ShawnWayneDu** [comment]
from tkinter import *
from tkinter import ttk
root = Tk()
ttk.Button(root, text="Hello World").grid()
root.mainloop()
运行这个测试Tkinter代码也是没问题的

**Comment by ShawnWayneDu** [comment]
<img width="1303" alt="运行时产生的截图" src="https://user-images.githubusercontent.com/75626672/210959180-faa65036-3170-4a8d-81be-7cb6c2f3c464.png">
就只有摄像头 无GUI界面
<img width="1296" alt="注释掉process后的运行结果" src="https://user-images.githubusercontent.com/75626672/210959408-2df1aded-d68d-472a-826f-b806524a237c.png">

**Comment by coneypo** [comment]
- 摄像头的数据在左边：self.frame_left_camera.pack()
- 其他信息在右边：self.frame_right_info.pack()

1. 我这边开发环境是 Ubuntu，你那边是 MAC，默认的摄像头输入拿到的 `Frame Size` 可能比较大，`.pack()` 之后就装不下了，可以打印一下拿到的 `frame size` 看看，我设置整个 tkinter 的 GUI size 才 `self.win.geometry("1300x550")`
2. 你可以丢张 size 小一点的图片，替换摄像头的输入，放到左边去 `.pack()`，看能不能显示出来了
3. 把输入的摄像头 frame 设置小一点

**Comment by ShawnWayneDu** [comment]
感谢！通过把摄像头frame设置小一点成功解决问题，请问此项目的训练模型和人脸识别算法是什么呀？

**Comment by coneypo** [comment]
> 感谢！通过把摄像头frame设置小一点成功解决问题，请问此项目的训练模型和人脸识别算法是什么呀？

It's essentially a version of the ResNet-34 network from the paper Deep Residual Learning for Image Recognition by He, Zhang, Ren, and Sun with a few layers removed and the number of filters per layer reduced by half.

**Comment by coneypo** [comment]
```
# This is trained on the ibug 300-W dataset (https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/)
# Also note that this model file is designed for use with dlib's HOG face detector.
# That is, it expects the bounding boxes from the face detector to be aligned a certain way,
the way dlib's HOG face detector does it.
# It won't work as well when used with a face detector that produces differently aligned boxes,
# such as the CNN based mmod_human_face_detector.dat face detector.

predictor = dlib.shape_predictor("data/data_dlib/shape_predictor_68_face_landmarks.dat")
shape = predictor(img_rd, faces[i])

```

README里面有写

**Comment by ShawnWayneDu** [comment]
再次感谢！

**Comment by coneypo** [comment]
不客气，没有其他问题的话我就关掉这个 issue 了 :)
