### ISSUE TITLE
mkdir and makedirs

### ISSUE THREAD

**Issue by smileLikeSun** [coneypo/Dlib_face_recognition_from_camera#6]
https://github.com/coneypo/Dlib_face_recognition_from_camera/blob/dcd3eaabc72e6b43d0605f6ebe17287d640fc006/get_faces_from_camera.py#L50
如果不存在 data 文件夹，使用 mkdir 创建 ‘data/img_from_camera’ 文件夹则会报错。此时使用 makedirs 则没有问题。
我的理解是 mkdir 创建单层文件夹，而 makedirs 创建单个文件夹或者未存在文件夹下的文件夹

**Comment by coneypo** [comment]
嗯是的，如果整个 git clone 下来的文件目录是:
--introduiction
--data
  ---- data_dlib
  ---- data_faces_examples
--face_reco_from_camera.py
--......py
--......py

如果有 /data 路径，可以 mkdir("data/data_faces_from_camera/")
如果没有 /data 路径，不可以 mkdir("data/data_faces_from_camera/") (父级路径不存在)，只能makedirs("data/data_faces_from_camera/")

如果没把 /data 删掉不会有这个问题 😀

**Comment by coneypo** [comment]
Can I close this issue if nothing else wrong?

**Comment by smileLikeSun** [comment]
sure, thank you

**Comment by smileLikeSun** [comment]
OK, fine
