### ISSUE TITLE
There is a problem running features_extraction_to_csv. Py

### ISSUE THREAD

**Issue by JackMing0** [coneypo/Dlib_face_recognition_from_camera#8]
data/data_faces_from_camera/person_1
正在读的人脸图像 / image to read:                data/data_faces_from_camera/person_1/img_face_1.jpg
检测到人脸的图像 / image with faces detected:    data/data_faces_from_camera/person_1/img_face_1.jpg 

Illegal instruction: 4 -------->There is a problem

Problem specification：
MAC OS: 10.13.6
Machine: 2010
Line 45: face_descriptor = face_rec.compute_face_descriptor(img_gray, shape); Part of this analysis: there may be a problem with the dlib library! So lead to: appear prompt illegal instruction: 4 have not found a solution!

**Comment by coneypo** [comment]
I have tried this repo in Ubuntu or Windows, but haven't tried it in MAC OS:
It might be an issue caused by dlib in MAC OS;

Please try following code to verify if "face_reco" of dlib can work in your OS:

```
import dlib
import cv2
from skimage import io

# Use dlib model
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("data/data_dlib/shape_predictor_5_face_landmarks.dat")
face_rec = dlib.face_recognition_model_v1("data/data_dlib/dlib_face_recognition_resnet_model_v1.dat")

img_rd = io.imread("test.jpg")
img_gray = cv2.cvtColor(img_rd, cv2.COLOR_BGR2RGB)
faces = detector(img_gray, 1)

shape = predictor(img_gray, faces[0])
face_descriptor = face_rec.compute_face_descriptor(img_gray, shape)

print(face_descriptor)
```

**Comment by JackMings** [comment]
Dilb library is indeed the problem!
The running result of the above code is: illegal instruction :4;
Search the Internet for this question! Tried a lot of methods, all did not solve!
Please ask the blogger! How to compile and install Python's dilb library correctly?

My machine is 2010: does the CPU not support dilb library   ##compilation
Before I consulted about this method: https://github.com/davisking/dlib

**Comment by coneypo** [comment]
Build out the dlib libraray for MAC from source code?

Maybe you can try install with Anaconda for you MAC rather than build from source code:

1. Follow this link to enable Anaconda python in MAC: https://docs.anaconda.com/anaconda/install/mac-os/;
2. And try "pip3 install dlib" in Anaconda terminal;
3. Run python scripts of dlib in Anaconda python;
4. Check if "face_rec" is ok with Anaconda python;

**Comment by JackMings** [comment]
Thanks for the advice! But it still doesn't solve the problem!

I have referred to the official installation steps!

1, I download the source code in the official: http://dlib.net/
2. Extract the package and compile it:
           cd dlib;cd examples;mkdir build;cd build;cmake ..;cmake --build . --config Release

Some code problems occurred during the compilation process:

[ 25%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inflate.c.o
/Users/mac/dlib/dlib/external/zlib/inflate.c:1507:61: warning: shifting a negative signed value is
      undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.


[ 74%] Building CXX object CMakeFiles/train_object_detector.dir/train_object_detector.cpp.o
/Users/mac/dlib/examples/train_object_detector.cpp:65:45: warning: '/*' within block comment
      [-Wcomment]
      ./train_object_detector examples/faces/*.jpg -u1
                                            ^
1 warning generated.


[ 86%] Building CXX object CMakeFiles/face_detection_ex.dir/face_detection_ex.cpp.o
/Users/mac/dlib/examples/face_detection_ex.cpp:11:34: warning: '/*' within block comment [-Wcomment]
        ./face_detection_ex faces/*.jpg
                                 ^
1 warning generated.



Problem specification：
This is where the compilation went wrong! From compile progress 1 to 100% nothing else goes wrong! I looked at the source code error! Have a plenty of annotation not standard bring about! There are some places where there is a lack of space


3.  I ignored the previous error to install: python setup.py install
    Installation progress to 50% error!
     Explanation: this is one of the nice places! The basic error is the same


    /Users/mac/dlib/dlib/external/pybind11/include/pybind11/detail/internals.h:169:33: warning: 
      'PyThread_create_key' is deprecated [-Wdeprecated-declarations]
        internals_ptr->tstate = PyThread_create_key();
                                ^
/Users/mac/.pyenv/versions/3.7.3/include/python3.7m/pythread.h:95:43: note: 'PyThread_create_key'
      has been explicitly marked deprecated here
PyAPI_FUNC(int) PyThread_create_key(void) Py_DEPRECATED(3.7);
                                          ^
/Users/mac/.pyenv/versions/3.7.3/include/python3.7m/pyport.h:493:54: note: expanded from macro
      'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))



4.  Use pip3 list to see if dlib was installed successfully:

Python 3.7.3 (default, Apr 19 2019, 11:27:39) 
[Clang 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> dlib.DLIB_USE_CUDA
False
>>> print(dlib)
<module 'dlib' from '/Users/mac/.pyenv/versions/3.7.3/lib/python3.7/site-packages/dlib-19.17.0-py3.7-macosx-10.13-x86_64.egg/dlib.cpython-37m-darwin.so'>



5. Still prompt: illegal instruction: 4 when executing the following code
    eer:    face_descriptor = face_rec.compute_face_descriptor(img_gray, shape)


import dlib
import cv2
from skimage import io

# Use dlib model
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("data/data_dlib/shape_predictor_5_face_landmarks.dat")
face_rec = dlib.face_recognition_model_v1("data/data_dlib/dlib_face_recognition_resnet_model_v1.dat")

img_rd = io.imread("test.jpg")
img_gray = cv2.cvtColor(img_rd, cv2.COLOR_BGR2RGB)
faces = detector(img_gray, 1)

shape = predictor(img_gray, faces[0])
face_descriptor = face_rec.compute_face_descriptor(img_gray, shape)

print(face_descriptor)


Important: I have installed x11 and cmake, this is to view the online MAC installation dlib method

**Comment by coneypo** [comment]
Maybe you can create an issue of building dlib in Mac in dlib repo too.
I think you can get more help from them about building from source code.:smile:
