### ISSUE TITLE
In the implementation：get_faces_from_camera.py An error

### ISSUE THREAD

**Issue by JackMing0** [coneypo/Dlib_face_recognition_from_camera#9]
Could you please tell me how to solve this problem：

Traceback (most recent call last):
  File "get_faces_from_camera.py", line 103, in <module>
    img_gray = cv2.cvtColor(img_rd, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by coneypo** [comment]
It seems that this issue is also caused by python library in MAC OS and I haven't seen such issue in Windows or Ubuntu...
Maybe google can provide more help than me about enable dlib and opencv in MAC OS..

**Comment by JackMings** [comment]
Could you please tell me whether this is the method to install opencv：pip install opencv-python
The above problem I found in：   flag, img_rd = cap.read()    In this position

**Comment by JackMings** [comment]
Finally found the problem, when I execute the above procedures! My computer's photoreceptor noticed the bad light! Automatically terminates the application! And report an error! It's not the library! Should be the reason that the code is not perfect! What can bloggers do to solve this problem?

**Comment by JackMings** [comment]
After constant testing! It's not the photoreceptor! Is the camera receives when the light is weak! The RGB value of the screen is less than a certain value! Will automatically terminate the process! An error!

**Comment by coneypo** [comment]
Can you try with this python script to check that if your camera  work with opencv？

**Comment by JackMing0** [comment]
Have not found specific problem at present!You can test this by using objects
For example, use your cell phone to cover the camera. Don't cover it with your hands!About 10 seconds!The program will automatically close the process!And throw an error

**Comment by coneypo** [comment]
I have just tried like you said, run "python3 get_faces_from_camera.py" and cover the camera with my cell phone, 20s passed but nothing happened..
Can you show me the error log when the program shut down and exit? Thanks.

**Comment by JackMing0** [comment]
I wonder if your method is correct.When you cover your camera with your phone!The computer screen was almost black!Almost no light is coming in!When I test!As long as the light received by the camera is less than a certain value!Will terminate the process!An error!
Error reporting!Here are the questions！

**Comment by coneypo** [comment]
![image](https://user-images.githubusercontent.com/7233586/56792145-782bb400-683b-11e9-80f7-754ce20e0b78.png)

I covered the camera before opening the camera, and covered it all the time (The camera window is black all the time);
Still nothing happened when I was running the python script;

I think it might be the issue caused by you hardware or the configuration of your PC?

I still cannot reproduce the issue.. can you show me the way you did with more details and the screenshot?

**Comment by JackMing0** [comment]
![Uploading QQ截图20190426161638.png…]()
This is the situation when you test!I looked carefully!Find out when you're testing!The camera is not without light!It's just that the light is getting weaker!Generally this may not automatically end the process!The screen goes black when you cover the camera!This may happen!
I run tests with a certain amount of light without any problems!Above problem can appear when the light is weaker!I tested it on a laptop!The camera is the laptop!

**Comment by JackMing0** [comment]
![QQ截图20190426161638](https://user-images.githubusercontent.com/37831370/56793909-a7dcbb00-683f-11e9-9501-b50a7a4ab485.png)

**Comment by JackMing0** [comment]
I have the code for the upward check! The problems are found in:  
       flag, img_rd = cap.read()
       print(img_rd)

The return result is:none

So here's the problem：

Traceback (most recent call last):
  File "get_faces_from_camera.py", line 108, in <module>
    img_gray = cv2.cvtColor(img_rd, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by JackMing0** [comment]
The above problems were successfully solved!
After commencement of execution:cap.read()

Sometimes the first frame cannot be read! The result is: none
Solution: add judgment and you have a perfect solution

**Comment by coneypo** [comment]
Please check following code in the repo:

while cap.isOpened():
    flag, img_rd = cap.read()

isOpened is the function in opencv to check if cv.Capture() works (for us it is the frame from camera)

**Comment by JackMing0** [comment]
isOpend this function  There is no problem！
